import { type TCategories } from '../types/categories';

// fake data generated by chatGPT

export const fakeCategoriesAndProducts: TCategories[] = [
  {
    id: 1,
    categoryName: 'writing',
    backgroundColor: 'rgba(250,237,203,0.6)',
    href: 'writing',
    products: [
      {
        id: 1,
        name: 'IntelliBot',
        websiteURL: 'www.intellibot.com',
        category: 'writing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'IntelliBot to inteligentny asystent do tworzenia tekstów. Z łatwością pomoże Ci napisać artykuł, esej czy nawet powieść. Nie musisz się już martwić o blokadę twórczą, bo IntelliBot jest zawsze gotów do pracy!',
      },
      {
        id: 2,
        name: 'SmartAI',
        websiteURL: 'www.smartai.com',
        category: 'writing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'SmartAI to inteligentne narzędzie do pisania, które zrewolucjonizuje Twoje doświadczenie w tworzeniu treści. Dzięki SmartAI możesz szybko i łatwo generować teksty, które zachwycą czytelników.',
      },
      {
        id: 3,
        name: 'AIBrain',
        websiteURL: 'www.aibrain.com',
        category: 'writing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'AIBrain to zaawansowane narzędzie do pisania wspomagane sztuczną inteligencją. Tworzenie tekstów stało się teraz bardziej efektywne i przyjemne niż kiedykolwiek wcześniej. Przekonaj się sam!',
      },
      {
        id: 4,
        name: 'TextGenius',
        websiteURL: 'www.textgenius.com',
        category: 'writing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'TextGenius to narzędzie, które pomoże Ci w tworzeniu tekstów o wysokiej jakości. Dzięki niemu Twoje treści będą jeszcze bardziej profesjonalne!',
      },
      {
        id: 5,
        name: 'WriterAI',
        websiteURL: 'www.writerai.com',
        category: 'writing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'WriterAI to inteligentny asystent do pisania, który dostarcza gotowe rozwiązania dla Twoich projektów. Oszczędź czas i efektywnie twórz treści!',
      },
    ],
  },
  {
    id: 2,
    categoryName: 'productivity',
    backgroundColor: 'rgba(201,228,222,0.6)',
    href: 'productivity',
    products: [
      {
        id: 6,
        name: 'TaskMaster',
        websiteURL: 'www.taskmaster.com',
        category: 'productivity',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'TaskMaster to inteligentne narzędzie do zarządzania zadaniami. Planuj, śledź postępy i osiągaj cele z łatwością!',
      },
      {
        id: 7,
        name: 'SmartScheduler',
        websiteURL: 'www.smartscheduler.com',
        category: 'productivity',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'SmartScheduler to inteligentny kalendarz, który pomoże Ci zorganizować Twój czas. Nie przegap już żadnego ważnego wydarzenia!',
      },
      {
        id: 8,
        name: 'AIDoer',
        websiteURL: 'www.aidoer.com',
        category: 'productivity',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'AIDoer to asystent do codziennych zadań. Pozwól mu pomóc Ci w wykonywaniu obowiązków i osiągnij więcej! AIDoer to asystent do codziennych zadań. Pozwól mu pomóc Ci w wykonywaniu obowiązków i osiągnij więcej! AIDoer to asystent do codziennych zadań. Pozwól mu pomóc Ci w wykonywaniu obowiązków i osiągnij więcej!',
      },
      {
        id: 9,
        name: 'EffiBot',
        websiteURL: 'www.effibot.com',
        category: 'productivity',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'EffiBot to narzędzie do efektywnego zarządzania projektami. Bądź bardziej produktywny dzięki EffiBot!',
      },
      {
        id: 10,
        name: 'ProductivityPro',
        websiteURL: 'www.productivitypro.com',
        category: 'productivity',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'ProductivityPro to profesjonalne narzędzie do zwiększania efektywności pracy. Osiągaj swoje cele szybciej!',
      },
    ],
  },
  {
    id: 3,
    categoryName: 'video generating',
    backgroundColor: 'rgba(198,222,241,0.6)',
    href: 'video-generating',
    products: [
      {
        id: 11,
        name: 'VideoGenius',
        websiteURL: 'www.videogenius.com',
        category: 'video generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'VideoGenius to narzędzie do generowania wideo o wysokiej jakości. Twórz wspaniałe filmy i prezentacje bez trudu!',
      },
      {
        id: 12,
        name: 'SmartVideo',
        websiteURL: 'www.smartvideo.com',
        category: 'video generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'SmartVideo to inteligentne oprogramowanie do tworzenia wideo. Dzięki niemu Twoje filmy staną się jeszcze lepsze!',
      },
      {
        id: 13,
        name: 'AIVideoMaker',
        websiteURL: 'www.aivideomaker.com',
        category: 'video generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'AIVideoMaker to zaawansowane narzędzie do produkcji filmów. Odkryj nowe możliwości w tworzeniu wideo!',
      },
      {
        id: 14,
        name: 'FilmBot',
        websiteURL: 'www.filmbot.com',
        category: 'video generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'FilmBot to asystent do tworzenia filmów. Realizuj swoje pomysły filmowe z FilmBotem!',
      },
      {
        id: 15,
        name: 'VideoPro',
        websiteURL: 'www.videopro.com',
        category: 'video generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'VideoPro to profesjonalne narzędzie do edycji i generowania wideo. Stwórz wspaniałe filmy w prosty sposób!',
      },
    ],
  },
  {
    id: 4,
    categoryName: 'image generating',
    backgroundColor: 'rgba(219,205,240,0.6)',
    href: 'image-generating',
    products: [
      {
        id: 16,
        name: 'ImageGenius',
        websiteURL: 'www.imagegenius.com',
        category: 'image generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'ImageGenius to narzędzie do generowania obrazów i grafik. Twórz wizualne dzieła sztuki z łatwością!',
      },
      {
        id: 17,
        name: 'SmartImage',
        websiteURL: 'www.smartimage.com',
        category: 'image generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'SmartImage to inteligentne oprogramowanie do tworzenia grafiki. Daj wyraz swojej kreatywności z SmartImage!',
      },
      {
        id: 18,
        name: 'AIImageCreator',
        websiteURL: 'www.aiimagecreator.com',
        category: 'image generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'AIImageCreator to zaawansowane narzędzie do generowania obrazów. Twórz artystyczne dzieła z pomocą AIImageCreator!',
      },
      {
        id: 19,
        name: 'ArtBot',
        websiteURL: 'www.artbot.com',
        category: 'image generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'ArtBot to asystent do tworzenia sztuki. Wyraź swoją wizję artystyczną z ArtBotem!',
      },
      {
        id: 20,
        name: 'ImagePro',
        websiteURL: 'www.imagepro.com',
        category: 'image generating',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'ImagePro to profesjonalne narzędzie do edycji i generowania obrazów. Stwórz wspaniałe grafiki w prosty sposób!',
      },
    ],
  },
  {
    id: 5,
    categoryName: 'chatbots',
    backgroundColor: 'rgba(242,198,222,0.6)',
    href: 'chatbots',
    products: [
      {
        id: 21,
        name: 'ChatBotMaster',
        websiteURL: 'www.chatbotmaster.com',
        category: 'chatbots',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'ChatBotMaster to zaawansowany chatbot do obsługi klientów. Popraw jakość obsługi klienta z ChatBotMaster!',
      },
      {
        id: 22,
        name: 'SmartChat',
        websiteURL: 'www.smartchat.com',
        category: 'chatbots',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'SmartChat to inteligentny chatbot, który odpowiada na pytania użytkowników. Zautomatyzuj swoją obsługę klienta dzięki SmartChat!',
      },
      {
        id: 23,
        name: 'AIBot',
        websiteURL: 'www.aibot.com',
        category: 'chatbots',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'AIBot to asystent do komunikacji online. Pozwól AIBotowi rozmawiać z Twoimi klientami!',
      },
      {
        id: 24,
        name: 'BotGenius',
        websiteURL: 'www.botgenius.com',
        category: 'chatbots',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'BotGenius to inteligentny chatbot, który zwiększa zaangażowanie użytkowników. Osiągnij lepsze wyniki z BotGenius!',
      },
      {
        id: 25,
        name: 'ChatAssistant',
        websiteURL: 'www.chatassistant.com',
        category: 'chatbots',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'ChatAssistant to asystent do obsługi klienta. Ulepsz swoją obsługę klienta dzięki ChatAssistant!',
      },
    ],
  },
  {
    id: 6,
    categoryName: 'marketing',
    backgroundColor: 'rgba(247,217,196,0.6)',
    href: 'marketing',
    products: [
      {
        id: 26,
        name: 'MarketingGenius',
        websiteURL: 'www.marketinggenius.com',
        category: 'marketing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'MarketingGenius to narzędzie do inteligentnego marketingu. Zwiększ efektywność swoich kampanii dzięki MarketingGenius!',
      },
      {
        id: 27,
        name: 'SmartMarketer',
        websiteURL: 'www.smartmarketer.com',
        category: 'marketing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'SmartMarketer to inteligentny system do prowadzenia kampanii marketingowych. Osiągnij lepsze wyniki z SmartMarketer!',
      },
      {
        id: 28,
        name: 'AIMarketingPro',
        websiteURL: 'www.aimarketingpro.com',
        category: 'marketing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'AIMarketingPro to zaawansowane narzędzie do planowania strategii marketingowych. Zdobądź przewagę konkurencyjną z AIMarketingPro!',
      },
      {
        id: 29,
        name: 'AdBot',
        websiteURL: 'www.adbot.com',
        category: 'marketing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'AdBot to asystent do tworzenia reklam. Twórz skuteczne reklamy z AdBot!',
      },
      {
        id: 30,
        name: 'MarketingPro',
        websiteURL: 'www.marketingpro.com',
        category: 'marketing',
        videoURL: 'https://www.youtube.com/watch?v=o5MutYFWsM8',
        cost: 'free',
        description:
          'MarketingPro to profesjonalne narzędzie do planowania i realizacji kampanii marketingowych. Osiągnij sukces z MarketingPro!',
      },
    ],
  },
];
